// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netS.proto

#ifndef PROTOBUF_netS_2eproto__INCLUDED
#define PROTOBUF_netS_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_netS_2eproto();
void protobuf_AssignDesc_netS_2eproto();
void protobuf_ShutdownFile_netS_2eproto();

class NetParamterS;

// ===================================================================

class NetParamterS : public ::google::protobuf::Message {
 public:
  NetParamterS();
  virtual ~NetParamterS();

  NetParamterS(const NetParamterS& from);

  inline NetParamterS& operator=(const NetParamterS& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NetParamterS& default_instance();

  void Swap(NetParamterS* other);

  // implements Message ----------------------------------------------

  NetParamterS* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NetParamterS& from);
  void MergeFrom(const NetParamterS& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required fixed32 word_dim = 1;
  inline bool has_word_dim() const;
  inline void clear_word_dim();
  static const int kWordDimFieldNumber = 1;
  inline ::google::protobuf::uint32 word_dim() const;
  inline void set_word_dim(::google::protobuf::uint32 value);

  // required fixed32 hidden_dim = 2;
  inline bool has_hidden_dim() const;
  inline void clear_hidden_dim();
  static const int kHiddenDimFieldNumber = 2;
  inline ::google::protobuf::uint32 hidden_dim() const;
  inline void set_hidden_dim(::google::protobuf::uint32 value);

  // required fixed32 bptt_truncate = 3;
  inline bool has_bptt_truncate() const;
  inline void clear_bptt_truncate();
  static const int kBpttTruncateFieldNumber = 3;
  inline ::google::protobuf::uint32 bptt_truncate() const;
  inline void set_bptt_truncate(::google::protobuf::uint32 value);

  // required fixed32 epoch = 4;
  inline bool has_epoch() const;
  inline void clear_epoch();
  static const int kEpochFieldNumber = 4;
  inline ::google::protobuf::uint32 epoch() const;
  inline void set_epoch(::google::protobuf::uint32 value);

  // optional float learingRate = 5;
  inline bool has_learingrate() const;
  inline void clear_learingrate();
  static const int kLearingRateFieldNumber = 5;
  inline float learingrate() const;
  inline void set_learingrate(float value);

  // repeated float U = 6 [packed = true];
  inline int u_size() const;
  inline void clear_u();
  static const int kUFieldNumber = 6;
  inline float u(int index) const;
  inline void set_u(int index, float value);
  inline void add_u(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      u() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_u();

  // repeated float W = 7 [packed = true];
  inline int w_size() const;
  inline void clear_w();
  static const int kWFieldNumber = 7;
  inline float w(int index) const;
  inline void set_w(int index, float value);
  inline void add_w(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      w() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_w();

  // repeated float V = 8 [packed = true];
  inline int v_size() const;
  inline void clear_v();
  static const int kVFieldNumber = 8;
  inline float v(int index) const;
  inline void set_v(int index, float value);
  inline void add_v(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      v() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_v();

  // @@protoc_insertion_point(class_scope:NetParamterS)
 private:
  inline void set_has_word_dim();
  inline void clear_has_word_dim();
  inline void set_has_hidden_dim();
  inline void clear_has_hidden_dim();
  inline void set_has_bptt_truncate();
  inline void clear_has_bptt_truncate();
  inline void set_has_epoch();
  inline void clear_has_epoch();
  inline void set_has_learingrate();
  inline void clear_has_learingrate();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 word_dim_;
  ::google::protobuf::uint32 hidden_dim_;
  ::google::protobuf::uint32 bptt_truncate_;
  ::google::protobuf::uint32 epoch_;
  ::google::protobuf::RepeatedField< float > u_;
  mutable int _u_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > w_;
  mutable int _w_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > v_;
  mutable int _v_cached_byte_size_;
  float learingrate_;
  friend void  protobuf_AddDesc_netS_2eproto();
  friend void protobuf_AssignDesc_netS_2eproto();
  friend void protobuf_ShutdownFile_netS_2eproto();

  void InitAsDefaultInstance();
  static NetParamterS* default_instance_;
};
// ===================================================================


// ===================================================================

// NetParamterS

// required fixed32 word_dim = 1;
inline bool NetParamterS::has_word_dim() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NetParamterS::set_has_word_dim() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NetParamterS::clear_has_word_dim() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NetParamterS::clear_word_dim() {
  word_dim_ = 0u;
  clear_has_word_dim();
}
inline ::google::protobuf::uint32 NetParamterS::word_dim() const {
  // @@protoc_insertion_point(field_get:NetParamterS.word_dim)
  return word_dim_;
}
inline void NetParamterS::set_word_dim(::google::protobuf::uint32 value) {
  set_has_word_dim();
  word_dim_ = value;
  // @@protoc_insertion_point(field_set:NetParamterS.word_dim)
}

// required fixed32 hidden_dim = 2;
inline bool NetParamterS::has_hidden_dim() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NetParamterS::set_has_hidden_dim() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NetParamterS::clear_has_hidden_dim() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NetParamterS::clear_hidden_dim() {
  hidden_dim_ = 0u;
  clear_has_hidden_dim();
}
inline ::google::protobuf::uint32 NetParamterS::hidden_dim() const {
  // @@protoc_insertion_point(field_get:NetParamterS.hidden_dim)
  return hidden_dim_;
}
inline void NetParamterS::set_hidden_dim(::google::protobuf::uint32 value) {
  set_has_hidden_dim();
  hidden_dim_ = value;
  // @@protoc_insertion_point(field_set:NetParamterS.hidden_dim)
}

// required fixed32 bptt_truncate = 3;
inline bool NetParamterS::has_bptt_truncate() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NetParamterS::set_has_bptt_truncate() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NetParamterS::clear_has_bptt_truncate() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NetParamterS::clear_bptt_truncate() {
  bptt_truncate_ = 0u;
  clear_has_bptt_truncate();
}
inline ::google::protobuf::uint32 NetParamterS::bptt_truncate() const {
  // @@protoc_insertion_point(field_get:NetParamterS.bptt_truncate)
  return bptt_truncate_;
}
inline void NetParamterS::set_bptt_truncate(::google::protobuf::uint32 value) {
  set_has_bptt_truncate();
  bptt_truncate_ = value;
  // @@protoc_insertion_point(field_set:NetParamterS.bptt_truncate)
}

// required fixed32 epoch = 4;
inline bool NetParamterS::has_epoch() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NetParamterS::set_has_epoch() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NetParamterS::clear_has_epoch() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NetParamterS::clear_epoch() {
  epoch_ = 0u;
  clear_has_epoch();
}
inline ::google::protobuf::uint32 NetParamterS::epoch() const {
  // @@protoc_insertion_point(field_get:NetParamterS.epoch)
  return epoch_;
}
inline void NetParamterS::set_epoch(::google::protobuf::uint32 value) {
  set_has_epoch();
  epoch_ = value;
  // @@protoc_insertion_point(field_set:NetParamterS.epoch)
}

// optional float learingRate = 5;
inline bool NetParamterS::has_learingrate() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NetParamterS::set_has_learingrate() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NetParamterS::clear_has_learingrate() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NetParamterS::clear_learingrate() {
  learingrate_ = 0;
  clear_has_learingrate();
}
inline float NetParamterS::learingrate() const {
  // @@protoc_insertion_point(field_get:NetParamterS.learingRate)
  return learingrate_;
}
inline void NetParamterS::set_learingrate(float value) {
  set_has_learingrate();
  learingrate_ = value;
  // @@protoc_insertion_point(field_set:NetParamterS.learingRate)
}

// repeated float U = 6 [packed = true];
inline int NetParamterS::u_size() const {
  return u_.size();
}
inline void NetParamterS::clear_u() {
  u_.Clear();
}
inline float NetParamterS::u(int index) const {
  // @@protoc_insertion_point(field_get:NetParamterS.U)
  return u_.Get(index);
}
inline void NetParamterS::set_u(int index, float value) {
  u_.Set(index, value);
  // @@protoc_insertion_point(field_set:NetParamterS.U)
}
inline void NetParamterS::add_u(float value) {
  u_.Add(value);
  // @@protoc_insertion_point(field_add:NetParamterS.U)
}
inline const ::google::protobuf::RepeatedField< float >&
NetParamterS::u() const {
  // @@protoc_insertion_point(field_list:NetParamterS.U)
  return u_;
}
inline ::google::protobuf::RepeatedField< float >*
NetParamterS::mutable_u() {
  // @@protoc_insertion_point(field_mutable_list:NetParamterS.U)
  return &u_;
}

// repeated float W = 7 [packed = true];
inline int NetParamterS::w_size() const {
  return w_.size();
}
inline void NetParamterS::clear_w() {
  w_.Clear();
}
inline float NetParamterS::w(int index) const {
  // @@protoc_insertion_point(field_get:NetParamterS.W)
  return w_.Get(index);
}
inline void NetParamterS::set_w(int index, float value) {
  w_.Set(index, value);
  // @@protoc_insertion_point(field_set:NetParamterS.W)
}
inline void NetParamterS::add_w(float value) {
  w_.Add(value);
  // @@protoc_insertion_point(field_add:NetParamterS.W)
}
inline const ::google::protobuf::RepeatedField< float >&
NetParamterS::w() const {
  // @@protoc_insertion_point(field_list:NetParamterS.W)
  return w_;
}
inline ::google::protobuf::RepeatedField< float >*
NetParamterS::mutable_w() {
  // @@protoc_insertion_point(field_mutable_list:NetParamterS.W)
  return &w_;
}

// repeated float V = 8 [packed = true];
inline int NetParamterS::v_size() const {
  return v_.size();
}
inline void NetParamterS::clear_v() {
  v_.Clear();
}
inline float NetParamterS::v(int index) const {
  // @@protoc_insertion_point(field_get:NetParamterS.V)
  return v_.Get(index);
}
inline void NetParamterS::set_v(int index, float value) {
  v_.Set(index, value);
  // @@protoc_insertion_point(field_set:NetParamterS.V)
}
inline void NetParamterS::add_v(float value) {
  v_.Add(value);
  // @@protoc_insertion_point(field_add:NetParamterS.V)
}
inline const ::google::protobuf::RepeatedField< float >&
NetParamterS::v() const {
  // @@protoc_insertion_point(field_list:NetParamterS.V)
  return v_;
}
inline ::google::protobuf::RepeatedField< float >*
NetParamterS::mutable_v() {
  // @@protoc_insertion_point(field_mutable_list:NetParamterS.V)
  return &v_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_netS_2eproto__INCLUDED
